### ISSUE TITLE
Prometheus node exporter version update

### ISSUE THREAD

**Issue by artifact-staking** [DamjanOstrelic/Cardano-stuff#1]
I noticed that this very convenient script is pointing to an older version of the node exporter. You may want to consider updating the environment variable and the wget to point to the new version. Currently it is 1.1.2.

https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz

I appreciate your work!

**Comment by dostrelith678** [comment]
Thank you very much, updated.
